Offline Sync and Logout added.
icrc/openmrs-android-fhir pull request #97
Opened 2024-12-09 14:17 UTC by AdityaKBhadragond14

This PR fixes the following two issues:
https://github.com/icrc/openmrs-android-fhir/issues/65
https://github.com/icrc/openmrs-android-fhir/issues/66

2024-12-10 06:42 UTC, parthfloyd requested changes
Great work! @AdityaKBhadragond14 
LGTM, with these minor changes. 

Please feel free to reach out if you've any questions.

2024-12-10 06:42 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +  private fun getUserChoice(): String? {
unused function, can be removed?

2024-12-10 06:42 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +          saveLoginExpiryChoice(getString(R.string.yes))
Is there any intended effect of saveLoginExpiryChoice?

2024-12-10 06:42 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +  private suspend fun navigateToLogin() {
suspend can be removed, along with line 307

2024-12-10 06:42 UTC, parthfloyd commented on core/src/main/AndroidManifest.xml
> +    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
Can be moved to app/src/main/AndroidManifest.xml & remove this file.

2024-12-11 06:27 UTC, AdityaKBhadragond14 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +  private fun getUserChoice(): String? {
I had kept this function in case if we need to use the login expiry choice in the future.

2024-12-11 06:27 UTC, AdityaKBhadragond14 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +          saveLoginExpiryChoice(getString(R.string.yes))
There is no intended effect but in the issue ticket it is mentioned to save the choice.

2024-12-11 06:44 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +          saveLoginExpiryChoice(getString(R.string.yes))
Noted! For this we may have to handle the "No, and don’t ask me again" choice. 
Overall, if user selects this option then app handles the following:
1. Periodic sync is stopped
2. the sync prompt is not displayed again. (Until the app is reopened). 

We can even refactor code to just save the third choice's value as boolean and handle it.

2024-12-11 06:46 UTC, AdityaKBhadragond14 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +          saveLoginExpiryChoice(getString(R.string.yes))
Yes that sounds good. We can do that.

2024-12-12 07:57 UTC, nsabale7 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +    tokenExpiryHandler?.post(tokenCheckRunnable!!)
add null check for `tokenCheckRunnable`, avoid adding not-null assertion operator without a check.

2024-12-12 07:58 UTC, nsabale7 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +          Toast.makeText(this, "Sync: Terminated", Toast.LENGTH_SHORT).show()
this can also be moved strings.xml

2024-12-12 07:58 UTC, nsabale7 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +      15 * 60 * 1000,
even add this as a configurable property.

2024-12-12 08:04 UTC, icrc-fdeniger commented
> @AdityaKBhadragond14 As per today's discussion
> 
>     * if the user click on sync a login should appear if the token is expired and if offline
> 
>     * make the timeouts configurable (wherever applicable).

 * if the user click on sync a login should appear if the token is expired and if **online** I suppose
 * if the user click on sync and offline a message should say that the sync will restart as soon as online

2024-12-12 08:05 UTC, nsabale7 commented on core/src/main/java/org/openmrs/android/fhir/MainActivity.kt
> +    val sharedPreferences = getSharedPreferences(PREFS_NAME, MODE_PRIVATE)
check if there is a preference manager already created in the application, use if already present

2024-12-12 08:06 UTC, nsabale7 commented on core/src/main/res/layout/activity_main.xml
> +                android:id="@+id/offline_flag"
```suggestion
                android:id="@+id/network_status_flag"
```

2024-12-12 08:07 UTC, nsabale7 commented on core/src/main/res/layout/activity_main.xml
> +                layout="@layout/offline_flag_layout"
```suggestion
                layout="@layout/network_status_flag_layout"
```

2024-12-19 09:48 UTC, icrc-jofrancisco approved these changes

2024-12-20 06:54 UTC, parthfloyd approved these changes

2024-12-20 06:56 UTC, merged