Basic Authentication support to OpenMRS backend server
icrc/openmrs-android-fhir pull request #99
Opened 2024-12-20 07:58 UTC by nsabale7

This PR contains the following changes for Basic Authentication issue (#64)

1. Screen to enter credentials
2. Navigation to auth flow based on `auth.method` property.

Added below properties in `local.properties` file
```
auth_method=basic
basic_auth_expiry_hours=48
```

2024-12-24 06:39 UTC, parthfloyd requested changes
Thanks @nsabale7, great work on this.  
I tested with https://dev3.openmrs.org & login is working as expected.

However the following changes are required other than minor code refactor suggestions.
- Logout functionality needs to be refactored to support basic auth. (Reference: [OpenMRS auth](https://openmrs.atlassian.net/wiki/spaces/docs/pages/25469830/REST+Web+Services+API+For+Clients#Authentication)

Please feel free to ping me if you want me to add a commit on this.

2024-12-24 06:39 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/auth/AuthStateManager.kt
> +import android.util.Base64
```suggestion
```
Unused import

2024-12-24 06:39 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/KeystoreHelper.kt
> +      .setKeySize(256)
```suggestion
      .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
      .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
      .setRandomizedEncryptionRequired(true)
```
Using GCM for encryption.

2024-12-24 06:39 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/EncryptionHelper.kt
> +import javax.crypto.spec.IvParameterSpec
```suggestion
import javax.crypto.spec.GCMParameterSpec
```

2024-12-24 06:39 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/EncryptionHelper.kt
> +  private const val AES_TRANSFORMATION = "AES/CBC/PKCS7Padding"
```suggestion
  private const val AES_TRANSFORMATION = "AES/GCM/NoPadding"
  private const val GCM_TAG_LENGTH = 16
```

2024-12-24 06:39 UTC, parthfloyd commented on core/src/main/java/org/openmrs/android/fhir/EncryptionHelper.kt
> +    val ivSpec = IvParameterSpec(iv)
```suggestion
    val ivSpec = GCMParameterSpec(GCM_TAG_LENGTH * 8, iv)
```

2025-01-07 06:53 UTC, parthfloyd commented
Thanks @nsabale7 Code LGTM! 
We may need to update the documentation for basic auth in readme (I'll do it in doc. update PR).
I'm awaiting openmrs-dev server to be up to test out the basic logout func. Will merge then.

2025-01-09 15:09 UTC, nsabale7 commented
@parthfloyd I have commited changes for logout. Please review and test. Let me know if you face any issues. Thanks

2025-01-10 09:13 UTC, parthfloyd commented
> @parthfloyd I have commited changes for logout. Please review and test. Let me know if you face any issues. Thanks

LGTM! Logout functionality working as expected!

2025-01-10 09:17 UTC, parthfloyd approved these changes

2025-01-10 09:20 UTC, merged